### ISSUE TITLE
Attribute content-disposition-filename of resource-serializer not optional

### ISSUE THREAD

**Issue by frankweenink** [Armatiek/xslweb#15]
The attribute of content-disposition-filename is not optional. Leaving it out will return null values in the HTTP response:

Content-Disposition: inline;filename="null"; filename*=UTF-8''null

**Comment by maartenkroon** [comment]
Hi Frank,

The implementation of XSLWeb's Resource Serializer and the serving of static files in general is based on / is a sublass of a slightly modified version of (the excellent ;-) 3rd party servlet class [org.omnifaces.servlet.FileServlet](https://showcase.omnifaces.org/servlets/FileServlet) which supports fast NIO stuff, ETag, If-None-Match and If-Modified-Since caching requests headers, Range and If-Range ranging requests etc. 

This org.omnifaces.servlet.FileServlet always returns a "[Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)" header even if a "Save as" dialog is not necessary. In this case the nl.armatiek.xslweb.web.servlet.FileServlet subclass returns "false" in the overridden method isAttachment() and org.omnifaces.servlet.FileServlet will generate a Content-Disposition header with a value of "inline" (the default). 

But there is a bug indeed, in case no content-disposition-filename is set in the the XSLT,   nl.armatiek.xslweb.web.servlet.FileServlet returns null in the overriden method getAttachmentName() which results
 
Content-Disposition: inline;filename="null"; filename*=UTF-8''null

This bug is fixed in ddd52c31bda5d9568abc479f1baf63fc52a6ce26
 
Thanks for reporting!

Maarten
