### ISSUE TITLE
Nested pipelines and pass data as attributes using the req:set-attribute($name, $value) extension function

### ISSUE THREAD

**Issue by siebej** [Armatiek/xslweb#21]
In the [docs](https://github.com/Armatiek/xslweb/blob/master/docs/XSLWeb%20Developer%20Manual.adoc#4-nested-pipelines) :
You can pass data to the nested pipeline using reqular request parameters added to the url, but you can also pass data as attributes using the [req:set-attribute($name, $value)](https://github.com/Armatiek/xslweb/blob/master/docs/XSLWeb%20Developer%20Manual.adoc#request-functions) extension function.

Is there any way to recognise a nested pipeline call? Or are the above options the only way? 

i.e. I see that these properties in the request, can they be used?

```
1.  127.0.0.1 in <req:remote-addr>127.0.0.1</req:remote-addr>
2.  localname in <req:request-url>http://localname/xslweb/somewebapp</req:request-url>
```
And if using the second req:set-attribute option, is the code below the way you do that? 

```
<!-- Inside code to use a nested pipeline -->
<xsl:sequence select="req:set-attribute('nested','1')"/>
<xsl:sequence select="document('xslweb:///somewebapp/')"/>
```
```
<!-- Inside request-handler -->
  <xsl:template match="/req:request[req:method = 'GET' and req:path eq '/']">
    <xsl:choose>
      <xsl:when test="req:get-attribute('nested')='1'">

```

**Comment by maartenkroon** [comment]
Hi Siebe,

I am afraid there is no reliable way to recognize a request being an "internal" (nested) request without providing that information yourself. A remote address of 127.0.0.1 or the "localhost" domain will probably also be present in your local development environment or when XSLWeb runs behind a proxy server. 

Your example correctly shows how you can pass information to the internal request by providing a request attribute to the main/parent request. This request attribute will also be available in the internal/nested request.

One remark about your second code sample: the request attributes are also part of the request input document, so you can also use the information in there instead of using the req:get-attribute() extension function.

Regards,
Maarten
