### ISSUE TITLE
HTTP Status 405 – Method POST Not Allowed

### ISSUE THREAD

**Issue by siebej** [Armatiek/xslweb#22]
Hi maarten,

I have a pipeline step where i build a docx file(using zip:zip()). 
I cannot use the zip:zip-serializer to build that docx, because of a this file-name: [Content_Types].xml that is part of the docx-file.(Error: [Content_Types].xml" not found )

Therefore Im trying to use the [resource-serialization](https://armatiek.github.io/xslweb/XSLWeb%20Developer%20Manual.html#resource-serializer-step) step.

The final part of stop2docx/stop2docx.xsl of the-pipeline step looks like this:

`	  <resp:response status="200">
	    <resp:body>
	      <resser:resource-serializer path="{$docxUri}" content-type="application/vnd.openxmlformats-officedocument.wordprocessingml.document" content-disposition-filename="{$sDocName||'.docx'}"/>	  
	    </resp:body>
	  </resp:response>          
`

And the request dispatcher looks like this:

`
        <pipeline:transformer name="stop2docx"          xsl-path="stop2docx/stop2docx.xsl"/>
        <pipeline:resource-serializer name="resource"/>
`

This returns this error-message by Tomcat:

`
	<h1>HTTP Status 405 – Method Not Allowed</h1>
	<hr class="line" />
	<p><b>Type</b> Status Report</p>
	<p><b>Message</b> Method &quot;POST&quot; not supported</p>
	<p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the
		target resource.</p>
	<hr class="line" />
	<h3>Apache Tomcat/9.0.43 (Ubuntu)</h3>
`

I'm using this war: xslweb-war-v4.2.0.tar.gz

What amI doing wrong?

Regards Siebe

**Comment by siebej** [comment]
Resolved :

One should use the binary-serializer i.e. like this:

Now final part of stop2docx/stop2docx.xsl of the-pipeline step looks like this:

`        <resp:response status="200">
          <resp:headers>
            <resp:header name="Content-Disposition">attachment; filename="<xsl:value-of select="$sDocName"/>.docx"</resp:header>
            <resp:header name="Content-type">application/vnd.openxmlformats-officedocument.wordprocessingml.document</resp:header>
          </resp:headers>
          <resp:body>
            <resser:binary-serializer>
              <xsl:sequence select="file:read-binary($docxUri)"/>
            </resser:binary-serializer>	  
          </resp:body>
        </resp:response>
`

And the request dispatcher now looks like this:

`        <pipeline:transformer name="stop2docx"          xsl-path="stop2docx/stop2docx.xsl"/>
        <pipeline:binary-serializer name="binary"/>
`

**Comment by maartenkroon** [comment]
Hi Siebe,

The use of the [binary-serializer](https://armatiek.github.io/xslweb/XSLWeb%20Developer%20Manual.html#binary-serializer-step) in combination with [file:read-binary()](https://armatiek.github.io/xslweb/XSLWeb%20Developer%20Manual.html#expath-file-functions) is an option to solve this issue indeed, but it has a few drawbacks:
- It uses a lot of memory; the generated zip must be read in memory completely (instead of streamed to the client like resource-serializer does).
- The binary serializer does not support HTTP headers like "ETag", "If-None-Match" and "If-Modified-Since" caching requests, support for "Range" and "If-Range" ranging requests ([RFC7233](https://tools.ietf.org/html/rfc7233)) etc. But for your use case this might not be a big problem.

The reason resource-serializer does not support POST requests (hence the error message) is that it makes use of a (slightly) modified version of [org.omnifaces.servlet.FileServlet](https://showcase.omnifaces.org/servlets/FileServlet) (because of the functionality mentioned above), and this servlet only supports HEAD and GET requests. I don't think it is very complicated to let FileServlet also support POST request, I will look into that.

Maarten

**Comment by siebej** [comment]
Hi  Maarten,
On a different server(with the same xslweb-version and the same xslt's...maybe tomcat-version differs???) it complained about <resp:response status="200"> parent. 
It stopped complaning when removed that parent, but then there were no properties to set headers like name of file and content-type.
At the end I ended up using the zip:zip-serializer and worked around the Error: [Content_Types].xml" not found )-problem, by using:

` <zip:file-entry name="[Content_Types].xml" src="{pathToFileWithoutBrackets.xml}"/>`

Siebe

**Comment by maartenkroon** [comment]
What do you mean by '<resp:response status="200"> parent', what was the actual error message?

**Comment by siebej** [comment]
Hi Maarten

This error:
Error evaluating ((<resp:header {(attr{name=...}, ...)}/>, ...)) on line 310 column 53 of stop2docx.xsl:
  SXCH0003: org.xml.sax.SAXException: Binary serializer output has incorrect format  In template rule with match="/" on line 137 of stop2docx.xsl     invoked by xsl:apply-templates at file:///webapps/worxcorrect/xsl/stop2docx/stop2docx.xsl#113  In template rule with match="/" on line 103 of stop2docx.xslnet.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXException: Binary serializer output has incorrect format
  
  When this in pipeline-xsl:
    
![image](https://user-images.githubusercontent.com/2422662/154476569-d3739a2f-9583-4076-af11-22fe5866dc93.png)

and this in request-dispather:
![image](https://user-images.githubusercontent.com/2422662/154476725-89cfcb89-bf20-4445-bf2d-035996f3a81f.png)

The working alternative would be to use only :
![image](https://user-images.githubusercontent.com/2422662/154476866-17866442-cd7b-45be-96be-83cfb040ac7a.png)

but then there is no info on filename and content-type.

**Comment by maartenkroon** [comment]
See commit 54de3fe : binary-serializer now supports attributes "content-type", "content-disposition-filename" and "expire-time" (just like resource-serializer) 

See commit e878557 : resource-serializer now also can be used in the context of POST requests (in addition to GET and HEAD requests)

**Comment by siebej** [comment]
Thanks
